import manifest from './partnerLogos.generated.json';
import { normalizePartnerName } from './partnerLogoMatch';

/**
 * Lookup of partner logos generated by scripts/build-partner-logos.ts.
 * Regenerate after changing assets/Logo:  npx tsx scripts/build-partner-logos.ts
 */
const BY_KEY = new Map<string, string>(
  (manifest as { key: string; url: string }[]).map((e) => [e.key, e.url]),
);

/** Public URL of a partner's logo, or null when none was matched. */
export function partnerLogo(name: string): string | null {
  return BY_KEY.get(normalizePartnerName(name)) ?? null;
}
