-- Seed: active domestic (Indonesian) partners (PETRA Global / petra_io.partners)
-- Source: assets/Data/Domestic Partners.csv
-- Criteria: active on/after 2026-06-29; has MoU and/or MoA (IA-only excluded);
--           one row per institution (merged); trailing city suffix stripped from name.
-- All rows: country='Indonesia', region='Asia', kind='domestic'.
-- Generated: 452 institutions.
-- Re-runnable: skips a name that already exists in petra_io.partners.

insert into petra_io.partners (name, country, kind, region)
select v.name, v.country, 'domestic'::petra_io.partner_kind, v.region
from (values
  ('Academy Computer Security Incident Response Team (ACAD CSIRT)', 'Indonesia', 'Asia'),
  ('Akademi Perawatan RS PGI Cikini', 'Indonesia', 'Asia'),
  ('Artax', 'Indonesia', 'Asia'),
  ('Asosiasi Dosen Pengabdian Kepada Masyarakat Indonesia', 'Indonesia', 'Asia'),
  ('Asosiasi Eksportir dan Produsen Handicract Indonesia (ASEPHI)', 'Indonesia', 'Asia'),
  ('Asosiasi Perguruan Tinggi Swasta Indonesia (APTISI) Wilayah VII Jatim', 'Indonesia', 'Asia'),
  ('Association of Chartered Cerified Accountants (ACCA) Indonesia', 'Indonesia', 'Asia'),
  ('Badan Arsip dan Perpustakaan Kota Surabaya', 'Indonesia', 'Asia'),
  ('Badan Musyawarah Antar Gereja (BAMAG) Kota Surabaya', 'Indonesia', 'Asia'),
  ('Badan Pengembangan Sumber Daya Manusia (BPSDM) Kementrian Komunikasi dan Informatika', 'Indonesia', 'Asia'),
  ('Badan Pengembangan Sumber Daya Manusia Industri Kementrian Perindustrian (PIDI)', 'Indonesia', 'Asia'),
  ('Balai Pemberdayaan Industri Persepatuan Indonesia (BPIPI)', 'Indonesia', 'Asia'),
  ('Bank Internasional Indonesia', 'Indonesia', 'Asia'),
  ('Bebras Indonesia', 'Indonesia', 'Asia'),
  ('BPK PENABUR Bandung', 'Indonesia', 'Asia'),
  ('Business Number Consulting (BNC)', 'Indonesia', 'Asia'),
  ('Chung Chung Christian School', 'Indonesia', 'Asia'),
  ('CV Agatha Management (AM Models)', 'Indonesia', 'Asia'),
  ('CV Benjamin Gideon & Associates', 'Indonesia', 'Asia'),
  ('CV C PLUS C Desain Komunikasi (C+C&Co)', 'Indonesia', 'Asia'),
  ('CV Zentax Consulting', 'Indonesia', 'Asia'),
  ('CV. Jalan Cerita Kesuksesan (JCK Enterprise)', 'Indonesia', 'Asia'),
  ('CV. Mycon Indonesia', 'Indonesia', 'Asia'),
  ('Direktorat Jenderal Kekayaan Intelektual Kementerian Hukum dan Hak Asasi Manusia Republik Indonesia', 'Indonesia', 'Asia'),
  ('Elyon Christian School', 'Indonesia', 'Asia'),
  ('Foreign Policy Community of Indonesia (FPCI)', 'Indonesia', 'Asia'),
  ('Forum Komunikasi Bidang Teknologi Informasi dan Komunikasi Badan Kerjasama Perguruan Tinggi Kristen di Indonesia (FTIK-BKPTKI)', 'Indonesia', 'Asia'),
  ('Forum Perpustakaan Perguruan Tinggi Indonesia (FPPTI) Jawa Tengah', 'Indonesia', 'Asia'),
  ('Four Points By Sheraton Surabaya', 'Indonesia', 'Asia'),
  ('GENARTA Collection', 'Indonesia', 'Asia'),
  ('Gereja Kristen Jawi Wetan (GKJW)', 'Indonesia', 'Asia'),
  ('Gereja Kristen Kalam Kudus (GKKK) Nanga Pinoh', 'Indonesia', 'Asia'),
  ('Gereja Sidang Jemaat Allah Eben Haezer (GSJA)', 'Indonesia', 'Asia'),
  ('German Academic Exchange Service (DAAD) Indonesia', 'Indonesia', 'Asia'),
  ('GII Commerce', 'Indonesia', 'Asia'),
  ('Gramedia Specialized Publications', 'Indonesia', 'Asia'),
  ('Handyman Smart Home', 'Indonesia', 'Asia'),
  ('Harian Pagi Kompas', 'Indonesia', 'Asia'),
  ('Harian Pagi Surya', 'Indonesia', 'Asia'),
  ('Harian Sore Surabaya Post (PT. Surabaya Post)', 'Indonesia', 'Asia'),
  ('Harian Suara Pembaruan', 'Indonesia', 'Asia'),
  ('Himpunan Desainer Interior Indonesia (HDII)', 'Indonesia', 'Asia'),
  ('Hotel Double Tree by Hilton Surabaya', 'Indonesia', 'Asia'),
  ('IDP South Jakarta', 'Indonesia', 'Asia'),
  ('Ikatan Akuntan Indonesia (IAI) Jatim', 'Indonesia', 'Asia'),
  ('Ikatan Arsitek Indonesia (IAI) Indonesia (Nasional)', 'Indonesia', 'Asia'),
  ('Ikatan Arsitek Indonesia (IAI) Jatim', 'Indonesia', 'Asia'),
  ('Ikatan Citra Alumni Taiwan Indonesia (ICATI) Jawa Timur', 'Indonesia', 'Asia'),
  ('Ikatan Konsultan Pajak Indonesia (IKPI)', 'Indonesia', 'Asia'),
  ('Indonesia Cyber Education Institute (ICE Institute)', 'Indonesia', 'Asia'),
  ('Indonesian Fashion Chamber', 'Indonesia', 'Asia'),
  ('Indoprima Group', 'Indonesia', 'Asia'),
  ('Institut Akuntan Publik Indonesia (IAPI), Jakarta Selatan', 'Indonesia', 'Asia'),
  ('Institut Bisnis & Multimedia Asmi', 'Indonesia', 'Asia'),
  ('Institut Francais Indonesia/Institut Prancis Indonesia (IFI)', 'Indonesia', 'Asia'),
  ('Institut Ilmu Kesehatan Bhakti Wiyata (IIK Bhakta) (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Institut Kesehatan Helvetia', 'Indonesia', 'Asia'),
  ('Institut Kesehatan Helvetia (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Institut Kesehatan Immanuel', 'Indonesia', 'Asia'),
  ('Institut Pertanian Bogor (IPB)', 'Indonesia', 'Asia'),
  ('Institut Teknologi dan Bisnis Asia Malang', 'Indonesia', 'Asia'),
  ('Institut Teknologi dan Bisnis Asia Malang (Pascasarjana Institut Teknologi dan Bisnis Asia Malang)', 'Indonesia', 'Asia'),
  ('Institut Teknologi Del', 'Indonesia', 'Asia'),
  ('Institut Teknologi Harapan Bangsa (ITHB)', 'Indonesia', 'Asia'),
  ('Institut Teknologi Nasional Bandung (ITENAS)', 'Indonesia', 'Asia'),
  ('Institut Teknologi Nasional Bandung (ITENAS) (Fakultas Arsitektur dan Desain ITENAS)', 'Indonesia', 'Asia'),
  ('Institut Teknologi Nasional Bandung (ITENAS) (Fakultas Teknik Sipil dan Perencanaan ITENAS)', 'Indonesia', 'Asia'),
  ('Institut Teknologi Nasional Bandung (ITENAS) (Fakultas Teknologi Industri ITENAS)', 'Indonesia', 'Asia'),
  ('Jakarta International University (JIU)', 'Indonesia', 'Asia'),
  ('Kantor Wilayah DJP Jawa Timur I Direktorat Jenderal Pajak Kementerian Keuangan Republik Indonesia', 'Indonesia', 'Asia'),
  ('Keluarga Bahasa Perancis Surabaya (KBPS)', 'Indonesia', 'Asia'),
  ('Kerukunan Usaha Kecil dan Menengah Indonesia (KUKMI) Tingkat 1 Jawa Timur Divisi Penerbitan, Grafika, dan Mass Media', 'Indonesia', 'Asia'),
  ('Komisi Nasional Disabilitas Republik Indonesia', 'Indonesia', 'Asia'),
  ('Komunitas "Surabaya Tempo Dulu"', 'Indonesia', 'Asia'),
  ('Kumpulan Alumni Teknik Sipil 1979', 'Indonesia', 'Asia'),
  ('Lembaga Alkitab Indonesia (LAI)', 'Indonesia', 'Asia'),
  ('Lembaga Konseling Keluarga Kreatif (LK3)', 'Indonesia', 'Asia'),
  ('Lembaga Pelatihan Kerja - Mitra Kalyana Sejahtera (LPK-MKS)', 'Indonesia', 'Asia'),
  ('Lembaga Sertifikasi Profesi - Mitra Kalyana Sejahtera (LSP-MKS)', 'Indonesia', 'Asia'),
  ('LSP Financial Planning Standards Board Indonesia (LSP FPSB Indonesia)', 'Indonesia', 'Asia'),
  ('M.E. Social Media Management', 'Indonesia', 'Asia'),
  ('Majelis Pendidikan Kristen di Indonesia (MPK)', 'Indonesia', 'Asia'),
  ('Mari Works', 'Indonesia', 'Asia'),
  ('Maspion Group', 'Indonesia', 'Asia'),
  ('Mawar Sharon Christian School (MSCS)', 'Indonesia', 'Asia'),
  ('Mayapada Group', 'Indonesia', 'Asia'),
  ('Mayapada Hospital', 'Indonesia', 'Asia'),
  ('MMA Center', 'Indonesia', 'Asia'),
  ('OMNI IT Consulting', 'Indonesia', 'Asia'),
  ('Ozora Yatrapaktaja', 'Indonesia', 'Asia'),
  ('PB Taxand', 'Indonesia', 'Asia'),
  ('Pemerintah Desa Miagan', 'Indonesia', 'Asia'),
  ('Pemerintah Desa Mojotrisno', 'Indonesia', 'Asia'),
  ('Pemerintah Kabupaten Maluku Tengah', 'Indonesia', 'Asia'),
  ('Pemerintah Kabupaten Sumba Barat', 'Indonesia', 'Asia'),
  ('Pemerintah Kabupaten Sumba Barat Daya', 'Indonesia', 'Asia'),
  ('Pemerintah Kabupaten Sumba Timur', 'Indonesia', 'Asia'),
  ('Pemerintah Kota Surabaya', 'Indonesia', 'Asia'),
  ('Pemerintahan Kabupaten Kaimana', 'Indonesia', 'Asia'),
  ('Perkumpulan Prakarsa Jaringan Cerdas Indonesia (PJCI)', 'Indonesia', 'Asia'),
  ('Perkumpulan Project Management Indonesia/Project Management Institute Indonesia Chapter (PMIIC)', 'Indonesia', 'Asia'),
  ('Perkumpulan Talenta Karya Sentosa', 'Indonesia', 'Asia'),
  ('Perpustakaan dan Pusat Layanan Digital Universitas Muhammadiyah Surakarta', 'Indonesia', 'Asia'),
  ('Perpustakaan Fakultas Hukum Universitas 17 Agustus 1945 Semarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Institut Agama Islam Negeri Kudus', 'Indonesia', 'Asia'),
  ('Perpustakaan Politeknik Harapan Bersama', 'Indonesia', 'Asia'),
  ('Perpustakaan Politeknik Ilmu Pelayaran Semarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Politeknik Maritim Negeri Indonesia', 'Indonesia', 'Asia'),
  ('Perpustakaan Politeknik Negeri Cilacap', 'Indonesia', 'Asia'),
  ('Perpustakaan Sekolah Tinggi Ilmu Ekonomi Pariwisata Indonesia', 'Indonesia', 'Asia'),
  ('Perpustakaan Sekolah Tinggi Ilmu Kesehatan Ibnu Sina Ajibarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Sekolah Tinggi Teknik Wiworotomo', 'Indonesia', 'Asia'),
  ('Perpustakaan STIKES Ngesti Waluyo Temanggung', 'Indonesia', 'Asia'),
  ('Perpustakaan STIKES Telogorejo Semarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Univeristas Islam Nahdlatul Ulama Jepara', 'Indonesia', 'Asia'),
  ('Perpustakaan Univeristas Islam Negeri Walisongo Semarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Univeristas Muria Kudus', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas ''Aisyiyah Surakarta', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas 17 Agustus 1945 (UNTAG) Semarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Al-Irsyad Cilacap', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Islam Batik Surakarta', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Islam Negeri K.H. Abdurrahman Wahid Pekalongan', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Islam Negeri Profesor Kiai Haji Saifuddin Zuhri Purwokerto', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Islam Negeri Salatiga', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Islam Sultan Agung', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Kusuma Husada Surakarta', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Muhadi Setiabudi', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Muhammadiyah Gombong', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Muhammadiyah Magelang', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Muhammadiyah Purwokerto', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Nahdlatul Ulama Al Ghazali Cilacap', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Pancasakti Tegal', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Pekalongan', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Sains Al-Qur''an', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Sebelas Maret', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Setia Budi', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Stikubank Semarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Tidar', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Wahid Hasyim Semarang', 'Indonesia', 'Asia'),
  ('Perpustakaan Universitas Widya Dharma Klaten', 'Indonesia', 'Asia'),
  ('Persatuan Dokter Gigi Indonesia Wilayah Jawa Timur (PDGI)', 'Indonesia', 'Asia'),
  ('Persatuan Perusahaan Periklanan Indonesia (P3I)', 'Indonesia', 'Asia'),
  ('Perserikatan Kurator dan Pengurus Indonesia (PKPI)', 'Indonesia', 'Asia'),
  ('Perusahaan Umum Daerah Air Minum Surya Sembada Kota Surabaya (PDAM)', 'Indonesia', 'Asia'),
  ('Politeknik Negeri Malang', 'Indonesia', 'Asia'),
  ('Poshana', 'Indonesia', 'Asia'),
  ('PPPK Petra', 'Indonesia', 'Asia'),
  ('PT Agro Mitra Alimentare (AMA)', 'Indonesia', 'Asia'),
  ('PT Ares Kusuma Raya', 'Indonesia', 'Asia'),
  ('PT Aruna Veda Kreasi', 'Indonesia', 'Asia'),
  ('PT Asia Bina Parama (English 1 Swara Group)', 'Indonesia', 'Asia'),
  ('PT Astra Sedaya Finance', 'Indonesia', 'Asia'),
  ('PT Asuransi Jiwa Bumi Asih Jaya', 'Indonesia', 'Asia'),
  ('PT Asuransi Mega Pratama', 'Indonesia', 'Asia'),
  ('PT Avia Avian', 'Indonesia', 'Asia'),
  ('PT Ayena Mandiri Sinema (Ayena Studio)', 'Indonesia', 'Asia'),
  ('PT Bakels Indonesia', 'Indonesia', 'Asia'),
  ('PT Bambang Djaja', 'Indonesia', 'Asia'),
  ('PT Bank Central Asia Tbk (BCA)', 'Indonesia', 'Asia'),
  ('PT Bank Mandiri (Persero) Tbk', 'Indonesia', 'Asia'),
  ('PT Bank Mayapada Internasional Tbk (Bank Mayapada)', 'Indonesia', 'Asia'),
  ('PT Bank Negara Indonesia (Persero) Tbk, Jakarta Pusat', 'Indonesia', 'Asia'),
  ('PT Bank Pembangunan Daerah Jawa Timur Tbk (Bank Jatim)', 'Indonesia', 'Asia'),
  ('PT Berca Hardayaperkasa', 'Indonesia', 'Asia'),
  ('PT Berpikir Revolusioner Indonesia (Narasio)', 'Indonesia', 'Asia'),
  ('PT Biochem Technology', 'Indonesia', 'Asia'),
  ('PT Boga Inti (Boga Group)', 'Indonesia', 'Asia'),
  ('PT Bukit Vista Nusantara', 'Indonesia', 'Asia'),
  ('PT Bursa Efek Indonesia (BEI)', 'Indonesia', 'Asia'),
  ('PT Centurion Perkasa Iman (Hotel Royal Tulip)', 'Indonesia', 'Asia'),
  ('PT Citra Sukses Analis', 'Indonesia', 'Asia'),
  ('PT Creosis International', 'Indonesia', 'Asia'),
  ('PT Cross Network Indonesia', 'Indonesia', 'Asia'),
  ('PT Deus Digital Tranformasi Universal', 'Indonesia', 'Asia'),
  ('PT Dinamika Manajemen Investama (Duo Dinamika Consultant)', 'Indonesia', 'Asia'),
  ('PT Dora Bisnis Konsultindo', 'Indonesia', 'Asia'),
  ('PT Dunia Bayar Indonesia (AiYO)', 'Indonesia', 'Asia'),
  ('PT Elefante Infradiji Solusi', 'Indonesia', 'Asia'),
  ('PT ePac Flexibles Indonesia', 'Indonesia', 'Asia'),
  ('PT Erajaya Swasembada, Tbk', 'Indonesia', 'Asia'),
  ('PT GoTo Gojek Tokopedia Tbk', 'Indonesia', 'Asia'),
  ('PT Grab Teknologi Indonesia', 'Indonesia', 'Asia'),
  ('PT Graha Inti Jaya', 'Indonesia', 'Asia'),
  ('PT Grant Thornton Indonesia', 'Indonesia', 'Asia'),
  ('PT Hafele Indotama', 'Indonesia', 'Asia'),
  ('PT Harmoni Byakta Akasha (HBA Indonesia)', 'Indonesia', 'Asia'),
  ('PT Hatsonsurya Electric (Hartono)', 'Indonesia', 'Asia'),
  ('PT HM Sampoerna', 'Indonesia', 'Asia'),
  ('PT IDNFT Menuju Bulan', 'Indonesia', 'Asia'),
  ('PT Indah Forindo (Clayxible)', 'Indonesia', 'Asia'),
  ('PT Indo Ceria Plastik dan Printing', 'Indonesia', 'Asia'),
  ('PT Industrial Robotic Automation (IRA)', 'Indonesia', 'Asia'),
  ('PT Insera Sena', 'Indonesia', 'Asia'),
  ('PT Intidaya Dinamika Sejati', 'Indonesia', 'Asia'),
  ('PT Kepuh Kencana Arum', 'Indonesia', 'Asia'),
  ('PT Kinobi Technologies Indonesia', 'Indonesia', 'Asia'),
  ('PT Lautan Natural Krimerindo', 'Indonesia', 'Asia'),
  ('PT Layo Seng Fong', 'Indonesia', 'Asia'),
  ('PT Lentera Edukasi Global (LEG)', 'Indonesia', 'Asia'),
  ('PT Lingkar Indonesia Unggul (ISCEA Indonesia)', 'Indonesia', 'Asia'),
  ('PT Mahaghora', 'Indonesia', 'Asia'),
  ('PT Martina Berto Tbk (Marta Tilaar)', 'Indonesia', 'Asia'),
  ('PT Merlin Gerin Indonesia', 'Indonesia', 'Asia'),
  ('PT Mitra Akademi Perkasa', 'Indonesia', 'Asia'),
  ('PT Mitra Akselerasi Bersama (MAB Consulting)', 'Indonesia', 'Asia'),
  ('PT Multi Spunindo Jaya', 'Indonesia', 'Asia'),
  ('PT Murni Solusindo Nusantara', 'Indonesia', 'Asia'),
  ('PT Nipsea Paints and Chemicals (Nippon Paint)', 'Indonesia', 'Asia'),
  ('PT Nusatama Properta Panbil', 'Indonesia', 'Asia'),
  ('PT Nutrifood Indonesia', 'Indonesia', 'Asia'),
  ('PT Odoo Software Indonesia', 'Indonesia', 'Asia'),
  ('PT Pasagung Anthrakia Semesta', 'Indonesia', 'Asia'),
  ('PT Pertamina (Persero)', 'Indonesia', 'Asia'),
  ('PT Populix Informasi Teknologi', 'Indonesia', 'Asia'),
  ('PT Propan Raya I.C.C, Sidoarjo', 'Indonesia', 'Asia'),
  ('PT Purindo Solusi Prosper (DPO&Co)', 'Indonesia', 'Asia'),
  ('PT Rekso Nasional Food (McDonald''s)', 'Indonesia', 'Asia'),
  ('PT Salam Pacific Indonesia Lines (PT. SPIL)', 'Indonesia', 'Asia'),
  ('PT Samaya Multikarya Sentosa', 'Indonesia', 'Asia'),
  ('PT Sarana Solusindo Informatika (SOLUSI)', 'Indonesia', 'Asia'),
  ('PT Satoria Agro Industri', 'Indonesia', 'Asia'),
  ('PT Schneider Indonesia', 'Indonesia', 'Asia'),
  ('PT Semen Imasco Asiatic', 'Indonesia', 'Asia'),
  ('PT Sinarmas Sekuritas', 'Indonesia', 'Asia'),
  ('PT Sinergi Daya Mitra (SDM)', 'Indonesia', 'Asia'),
  ('PT Sumber Djaja Perkasa', 'Indonesia', 'Asia'),
  ('PT Surabaya Wire', 'Indonesia', 'Asia'),
  ('PT Surya Mitra Internet', 'Indonesia', 'Asia'),
  ('PT Surya Multi Cemerlang', 'Indonesia', 'Asia'),
  ('PT Surya Sarana Dinamika (SSD)', 'Indonesia', 'Asia'),
  ('PT Surya Sukses Abadi Prima', 'Indonesia', 'Asia'),
  ('PT Surya Triniti Jaya (ArtGrass)', 'Indonesia', 'Asia'),
  ('PT Tancorp Abadi Nusantara', 'Indonesia', 'Asia'),
  ('PT Tangkas Cipta Optimal (TACO HPL)', 'Indonesia', 'Asia'),
  ('PT Taranium Rantai Blok Indonesia', 'Indonesia', 'Asia'),
  ('PT Tiga Dinamika Solusi Indonesia (3DS)', 'Indonesia', 'Asia'),
  ('PT Tokopedia', 'Indonesia', 'Asia'),
  ('PT ValuePlus Indoraya', 'Indonesia', 'Asia'),
  ('PT Visiniaga Mitra Kreasindo', 'Indonesia', 'Asia'),
  ('PT Wahana Kosmetika Indonesia', 'Indonesia', 'Asia'),
  ('PT Weefer Indonesia', 'Indonesia', 'Asia'),
  ('PT Welco', 'Indonesia', 'Asia'),
  ('PT. Berawal Dari Media (Socioworks)', 'Indonesia', 'Asia'),
  ('PT. Bintang Sempurna', 'Indonesia', 'Asia'),
  ('PT. Bosch Rexroth', 'Indonesia', 'Asia'),
  ('PT. Ceria Belajar Edukasi Indonesia (Wondermind)', 'Indonesia', 'Asia'),
  ('PT. Charoen Popkphand Indonesia Tbk - Jawa Timur', 'Indonesia', 'Asia'),
  ('PT. Damai Sejahtera Abadi, Tbk - (UFOE)', 'Indonesia', 'Asia'),
  ('PT. Fuboru Indonesia', 'Indonesia', 'Asia'),
  ('PT. Global Industri Teknologi Solusi (GITS)', 'Indonesia', 'Asia'),
  ('PT. Graha Alam Lestari (The Apurva Kempinski Bali)', 'Indonesia', 'Asia'),
  ('PT. Havanna Teguh Sadana', 'Indonesia', 'Asia'),
  ('PT. Himalaya Sinar Abadi', 'Indonesia', 'Asia'),
  ('PT. Jayamas Medica Industri, Tbk.', 'Indonesia', 'Asia'),
  ('PT. Kresna Karya Teknologi', 'Indonesia', 'Asia'),
  ('PT. Kuncie Pintar Nusantara', 'Indonesia', 'Asia'),
  ('PT. Mikatasa Agung', 'Indonesia', 'Asia'),
  ('PT. Mitra Kalyana Sejahtera (MKS)', 'Indonesia', 'Asia'),
  ('PT. Mitra Pinasthika Mulia (MPM)', 'Indonesia', 'Asia'),
  ('PT. PathGen Diagnostik Teknologi', 'Indonesia', 'Asia'),
  ('PT. Perusahaan Cat, Pernis, dan Kaleng Mataram (PT. Mataram Paint)', 'Indonesia', 'Asia'),
  ('PT. Piaget Indonesia', 'Indonesia', 'Asia'),
  ('PT. Platinum Ceramics Industry', 'Indonesia', 'Asia'),
  ('PT. Puri Padma Management (Padma Hotels)', 'Indonesia', 'Asia'),
  ('PT. Riliv Psikologi Indonesia', 'Indonesia', 'Asia'),
  ('PT. Semen Indonesia (Persero) Tbk.', 'Indonesia', 'Asia'),
  ('PT. Silverstream Indonesia Sehat', 'Indonesia', 'Asia'),
  ('PT. Sinar Cipta Lumindo (Lumine Studio)', 'Indonesia', 'Asia'),
  ('PT. Sinko Prima Alloy', 'Indonesia', 'Asia'),
  ('PT. SRC Indonesia Sembilan', 'Indonesia', 'Asia'),
  ('PT. Sun Paper Source (SPS Corporate)', 'Indonesia', 'Asia'),
  ('PT. Suparma Tbk', 'Indonesia', 'Asia'),
  ('PT. Tata Rapika Globalindo', 'Indonesia', 'Asia'),
  ('PT. Tirtakencana Tatawarna', 'Indonesia', 'Asia'),
  ('PT. Transforma Oto Prima (Mercedes-Benz)', 'Indonesia', 'Asia'),
  ('PT. Wiralab Analitika Solusindo', 'Indonesia', 'Asia'),
  ('Pusat Kebudayaan & Kerjasama Bahasa (CCCL)', 'Indonesia', 'Asia'),
  ('Revolt Industry', 'Indonesia', 'Asia'),
  ('RSM Indonesia', 'Indonesia', 'Asia'),
  ('Rumah Sakit Bhayangkara HS. Samsoeri Mertojoso', 'Indonesia', 'Asia'),
  ('Samator Group', 'Indonesia', 'Asia'),
  ('SD Negeri Siwalankerto II/419', 'Indonesia', 'Asia'),
  ('Sekolah Betzata', 'Indonesia', 'Asia'),
  ('Sekolah Buin Batu', 'Indonesia', 'Asia'),
  ('Sekolah Kristen IPEKA', 'Indonesia', 'Asia'),
  ('Sekolah Kristen Kalam Kudus (SKKK) Pematang Siantar', 'Indonesia', 'Asia'),
  ('Sekolah Luar Biasa (SLB) Siswa Budhi', 'Indonesia', 'Asia'),
  ('Sekolah Tinggi Ilmu Ekonomi (STIE) Malangkucecwara', 'Indonesia', 'Asia'),
  ('Sekolah Tinggi Informatika & Komputer Indonesia (STIKI) Malang', 'Indonesia', 'Asia'),
  ('Sekolah Tinggi Keguruan dan Ilmu Pendidikan Soe (STKIP Soe)', 'Indonesia', 'Asia'),
  ('Sekolah Tinggi Teologi (STT) Amadeus', 'Indonesia', 'Asia'),
  ('Sekolah Tinggi Teologi (STT) Tawangmangu', 'Indonesia', 'Asia'),
  ('Sekolah Tinggi Teologi (STT) Torsina', 'Indonesia', 'Asia'),
  ('Sekretariat Jenderal Kementerian Sosial', 'Indonesia', 'Asia'),
  ('Sending WEC Indonesia', 'Indonesia', 'Asia'),
  ('Sheraton Surabaya Hotel', 'Indonesia', 'Asia'),
  ('SMA Katolik Kolese Santo Yusup', 'Indonesia', 'Asia'),
  ('SMA Katolik Santo Augustinus', 'Indonesia', 'Asia'),
  ('SMA Katolik Santo Paulus', 'Indonesia', 'Asia'),
  ('SMA Katolik Santo Yoseph, Denpasar', 'Indonesia', 'Asia'),
  ('SMA Katolik Sedes Sapientiae', 'Indonesia', 'Asia'),
  ('SMA Regina Pacis', 'Indonesia', 'Asia'),
  ('SMA Vita School', 'Indonesia', 'Asia'),
  ('SMALB Siswa Budhi', 'Indonesia', 'Asia'),
  ('SMARCH Architecture Course', 'Indonesia', 'Asia'),
  ('SMP Negeri 57 Surabaya', 'Indonesia', 'Asia'),
  ('SMPLB-A YPAB Surabaya', 'Indonesia', 'Asia'),
  ('STIKES Bethesda Yakkum', 'Indonesia', 'Asia'),
  ('STISIP Widuri', 'Indonesia', 'Asia'),
  ('STITEK Dharma Yadi Makassar', 'Indonesia', 'Asia'),
  ('STMIK Widuri', 'Indonesia', 'Asia'),
  ('Surya Megah Expertindo', 'Indonesia', 'Asia'),
  ('Tanda Seru', 'Indonesia', 'Asia'),
  ('Tentara Nasional Indonesia Angkatan Laut (Sekolah Tinggi Teknologi Angkatan Laut / STTAL)', 'Indonesia', 'Asia'),
  ('The Institute of Chartered Accountants in England and Wales (ICAEW) Indonesia', 'Indonesia', 'Asia'),
  ('UIN Sunan Ampel', 'Indonesia', 'Asia'),
  ('Univeristas Mulawarman (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Abdurachman Saleh Situbondo (UNARS)', 'Indonesia', 'Asia'),
  ('Universitas Airlangga', 'Indonesia', 'Asia'),
  ('Universitas Alma Ata', 'Indonesia', 'Asia'),
  ('Universitas Almuslim', 'Indonesia', 'Asia'),
  ('Universitas Andalas', 'Indonesia', 'Asia'),
  ('Universitas Andalas (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Anwar Medika', 'Indonesia', 'Asia'),
  ('Universitas Atma Jaya Yogyakarta', 'Indonesia', 'Asia'),
  ('Universitas Baiturrahmah (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Bina Nusantara', 'Indonesia', 'Asia'),
  ('Universitas Brawijaya', 'Indonesia', 'Asia'),
  ('Universitas Ciputra Surabaya', 'Indonesia', 'Asia'),
  ('Universitas Ciputra Surabaya (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Dhyana Pura', 'Indonesia', 'Asia'),
  ('Universitas Dhyana Pura, Bali', 'Indonesia', 'Asia'),
  ('Universitas Dr. Soetomo', 'Indonesia', 'Asia'),
  ('Universitas Gadjah Mada (UGM)', 'Indonesia', 'Asia'),
  ('Universitas Halmahera (UNIERA)', 'Indonesia', 'Asia'),
  ('Universitas Hamzanwadi', 'Indonesia', 'Asia'),
  ('Universitas Hang Tuah', 'Indonesia', 'Asia'),
  ('Universitas Hang Tuah (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Hasanuddin (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Hayam Wuruk Perbanas', 'Indonesia', 'Asia'),
  ('Universitas HKBP Nommensen Medan', 'Indonesia', 'Asia'),
  ('Universitas Indonesia (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Islam Darul `Ulum Lamongan', 'Indonesia', 'Asia'),
  ('Universitas Islam Indonesia', 'Indonesia', 'Asia'),
  ('Universitas Islam Malang (Unisma)', 'Indonesia', 'Asia'),
  ('Universitas Islam Sultan Agung', 'Indonesia', 'Asia'),
  ('Universitas Islam Sultan Agung (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Jember (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Jenderal Ahmad Yani (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Jenderal Soedirman (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Kadiri (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Katolik Indonesia Atma Jaya', 'Indonesia', 'Asia'),
  ('Universitas Katolik Indonesia Santu Paulus Ruteng', 'Indonesia', 'Asia'),
  ('Universitas Katolik Parahyangan', 'Indonesia', 'Asia'),
  ('Universitas Katolik Soegijapranata', 'Indonesia', 'Asia'),
  ('Universitas Katolik Widya Mandala Surabaya (UKWMS)', 'Indonesia', 'Asia'),
  ('Universitas Katolik Widya Mandira', 'Indonesia', 'Asia'),
  ('Universitas Kristen Artha Wacana (UKAW)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Duta Wacana (UKDW)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Immanuel (UKRIM). Yogyakarta', 'Indonesia', 'Asia'),
  ('Universitas Kristen Indonesia (UKI)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Indonesia (UKI) Toraja', 'Indonesia', 'Asia'),
  ('Universitas Kristen Indonesia Maluku (UKIM)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Indonesia Maluku (UKIM), Maluku (Fakultas Ekonomi dan Bisnis UKIM)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Indonesia Paulus (UKIP)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Krida Wacana (UKRIDA)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Maranatha', 'Indonesia', 'Asia'),
  ('Universitas Kristen Palangka Raya', 'Indonesia', 'Asia'),
  ('Universitas Kristen Papua (UKIP Sorong)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Satya Wacana (Fakultas Sains dan Matematika)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Satya Wacana (UKSW)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Surakarta', 'Indonesia', 'Asia'),
  ('Universitas Kristen Tentena (UNKRIT)', 'Indonesia', 'Asia'),
  ('Universitas Kristen Wira Wacana (UNKRISWINA) Sumba', 'Indonesia', 'Asia'),
  ('Universitas Krsiten Indonesia Maluku', 'Indonesia', 'Asia'),
  ('Universitas Lambung Mangkurat (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Mahasaraswati (UNMAS)', 'Indonesia', 'Asia'),
  ('Universitas Mahasaraswati (UNMAS) (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Mega Buana Palopo', 'Indonesia', 'Asia'),
  ('Universitas Merdeka Pasuruan', 'Indonesia', 'Asia'),
  ('Universitas Methodist Indonesia (UMI)', 'Indonesia', 'Asia'),
  ('Universitas Muhammadiyah Malang', 'Indonesia', 'Asia'),
  ('Universitas Muhammadiyah Semarang (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Muhammadiyah Sidoarjo', 'Indonesia', 'Asia'),
  ('Universitas Muhammadiyah Sidoarjo (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Muhammadiyah Surabaya (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Muhammadiyah Surakarta (UMS) (Fakultas Teknik UMS)', 'Indonesia', 'Asia'),
  ('Universitas Muhammadiyah Yogyakarta (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Multimedia Nusantara', 'Indonesia', 'Asia'),
  ('Universitas Muslim Indonesia (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Nahdlatul Ulama Surabaya', 'Indonesia', 'Asia'),
  ('Universitas Narotama', 'Indonesia', 'Asia'),
  ('Universitas Nasional (Fakultas Ekonomi dan Bisnis)', 'Indonesia', 'Asia'),
  ('Universitas Negeri Surabaya (UNESA)', 'Indonesia', 'Asia'),
  ('Universitas Ottow Geissler Papua', 'Indonesia', 'Asia'),
  ('Universitas Padjadjaran', 'Indonesia', 'Asia'),
  ('Universitas Padjajaran (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Pelita Harapan (UPH) Karawaci', 'Indonesia', 'Asia'),
  ('Universitas Pembangunan Jaya', 'Indonesia', 'Asia'),
  ('Universitas Pendidikan Ganesha (Undiksha)', 'Indonesia', 'Asia'),
  ('Universitas PGRI Adi Buana Surabaya', 'Indonesia', 'Asia'),
  ('Universitas PGRI Kanjuruhan Malang', 'Indonesia', 'Asia'),
  ('Universitas Pradita', 'Indonesia', 'Asia'),
  ('Universitas Prima Nusantara Bukittinggi', 'Indonesia', 'Asia'),
  ('Universitas Prof. Dr. Moestopo Beragama (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Riau Kepulauan (UNRIKA)', 'Indonesia', 'Asia'),
  ('Universitas Sains Dan Teknologi Komputer (STEKOM)', 'Indonesia', 'Asia'),
  ('Universitas Sanata Dharma', 'Indonesia', 'Asia'),
  ('Universitas Sebelas Maret', 'Indonesia', 'Asia'),
  ('Universitas Sriwijaya (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Sumatera Utara (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Surabaya (UBAYA)', 'Indonesia', 'Asia'),
  ('Universitas Syah Kuala (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Universitas Telkom', 'Indonesia', 'Asia'),
  ('Universitas Triatma Mulya (UNTRIM)', 'Indonesia', 'Asia'),
  ('Universitas Tribuana Kalabahi', 'Indonesia', 'Asia'),
  ('Universitas Trisakti', 'Indonesia', 'Asia'),
  ('Universitas Udayana', 'Indonesia', 'Asia'),
  ('Universitas Widya Kartika (UWIKA)', 'Indonesia', 'Asia'),
  ('Universitas Widyatama', 'Indonesia', 'Asia'),
  ('Universitas Wisnuwardhana', 'Indonesia', 'Asia'),
  ('Universitas Yarsi (Fakultas Kedokteran Gigi)', 'Indonesia', 'Asia'),
  ('Vania Interior Furnishing', 'Indonesia', 'Asia'),
  ('Visualcast Designology (CV Signum Prospera)', 'Indonesia', 'Asia'),
  ('Vooya', 'Indonesia', 'Asia'),
  ('Wahana Visi Indonesia', 'Indonesia', 'Asia'),
  ('Wings Group Surabaya', 'Indonesia', 'Asia'),
  ('Wisma Jerman', 'Indonesia', 'Asia'),
  ('Yayasan Atedia Sumber Damai', 'Indonesia', 'Asia'),
  ('Yayasan Bantuan Kasih Indonesia (Compassion Indonesia Foundation)', 'Indonesia', 'Asia'),
  ('Yayasan Bersatu Membangun Bangsa', 'Indonesia', 'Asia'),
  ('Yayasan Caraka Mulia', 'Indonesia', 'Asia'),
  ('Yayasan Cinta Baca', 'Indonesia', 'Asia'),
  ('Yayasan Eben Haezar', 'Indonesia', 'Asia'),
  ('Yayasan Edukasi Inti Pratama (IDS College)', 'Indonesia', 'Asia'),
  ('Yayasan Exodus (REC)', 'Indonesia', 'Asia'),
  ('Yayasan Habitat Kemanusiaan Indonesia (YHKI)', 'Indonesia', 'Asia'),
  ('Yayasan Haggai Indonesia', 'Indonesia', 'Asia'),
  ('Yayasan Indonesia Sejahtera Barokah (YISB)', 'Indonesia', 'Asia'),
  ('Yayasan Kalam Kudus Indonesia (YKKI) Medan', 'Indonesia', 'Asia'),
  ('Yayasan Mawar Sharon Peduli', 'Indonesia', 'Asia'),
  ('Yayasan Medicom Charity', 'Indonesia', 'Asia'),
  ('Yayasan Monash University Indonesia (Monash University Indonesia)', 'Indonesia', 'Asia'),
  ('Yayasan ODB Indonesia', 'Indonesia', 'Asia'),
  ('Yayasan Pakta Peduli Indonesia', 'Indonesia', 'Asia'),
  ('Yayasan Pembangunan Berkelanjutan (YPB), Jakarta Selatan', 'Indonesia', 'Asia'),
  ('Yayasan Pendidikan Kristen (YPK) Gloria', 'Indonesia', 'Asia'),
  ('Yayasan Pendidikan Kristen (YPK) Jawa Timur', 'Indonesia', 'Asia'),
  ('Yayasan Pendidikan Kristen Gloria', 'Indonesia', 'Asia'),
  ('Yayasan Pendidikan Kristen Sunodia', 'Indonesia', 'Asia'),
  ('Yayasan Pondok Kasih', 'Indonesia', 'Asia'),
  ('Yayasan Sosial Kristen Salib Putih', 'Indonesia', 'Asia')
) as v(name, country, region)
where not exists (
  select 1 from petra_io.partners p where p.name = v.name and p.kind = 'domestic'
);
