-- Seed: active international partners (PETRA Global / petra_io.partners)
-- Source: assets/Data/International Partners.csv
-- Criteria: active on/after 2026-06-29; has MoU and/or MoA (IA-only excluded);
--           one row per institution (multiple agreements merged).
-- Generated: 161 institutions.
-- Re-runnable: skips a name that already exists in petra_io.partners.

insert into petra_io.partners (name, country, kind, region)
select v.name, v.country, 'international'::petra_io.partner_kind, v.region
from (values
  ('Academy of Finance & Management Australia (AFMA), Australia', 'Australia', 'Oceania'),
  ('ACECOMS Satellite Center', 'Thailand', 'Asia'),
  ('Acetrend Corporation SDN BHD (Pullman Kuala Lumpur City Centre Hotel & Residences), Malaysia', 'Malaysia', 'Asia'),
  ('AGH University of Science and Technology, Poland', 'Poland', 'Europe'),
  ('Amsterdam Faculty of Education / EFA (Educatieve Faculteit Amsterdam)', 'Netherlands', 'Europe'),
  ('Anhui University, China', 'China', 'Asia'),
  ('Asia Pacific University of Technology & Innovation (APU), Malaysia', 'Malaysia', 'Asia'),
  ('Asia University, Japan', 'Japan', 'Asia'),
  ('Asian Institute of Technology, Thailand', 'Thailand', 'Asia'),
  ('Assam Down Town University, India', 'India', 'Asia'),
  ('Association of Christian Universities and Colleges in Asia (ACUCA)', 'Korea', 'Asia'),
  ('Bangkok University, Thailand', 'Thailand', 'Asia'),
  ('Bicol University, Phillipines', 'Philippines', 'Asia'),
  ('Busan Digital University (BDU), Korea', 'Korea', 'Asia'),
  ('Busan University of Foreign Studies, Korea', 'Korea', 'Asia'),
  ('Cambodian University for Specialties (CUS), Cambodia', 'Cambodia', 'Asia'),
  ('Central Philippine University, Philippines', 'Philippines', 'Asia'),
  ('Centre for Innovation and Enterprise Pty Ltd (CIE), Australia', 'Australia', 'Oceania'),
  ('Chang Jung Christian University, Taiwan', 'Taiwan', 'Asia'),
  ('Changwon National University, Korea', 'Korea', 'Asia'),
  ('Chinese Culture University (CCU), Taiwan', 'Taiwan', 'Asia'),
  ('Chodang University, Korea', 'Korea', 'Asia'),
  ('Chung Yuan Christian University, Taiwan', 'Taiwan', 'Asia'),
  ('City University of Hong Kong (CityU), Hong Kong', 'Hong Kong', 'Asia'),
  ('Clark Memorial International High School, Japan', 'Japan', 'Asia'),
  ('CLO Virtual Fashion LLC', 'Hong Kong', 'Asia'),
  ('College of Global Hakka Studies', 'Taiwan', 'Asia'),
  ('Coventry University, UK', 'UK', 'Europe'),
  ('Crea Viae Education, Malaysia', 'Malaysia', 'Asia'),
  ('Daffodil International University, Bangladesh', 'Bangladesh', 'Asia'),
  ('Dallas Baptist University, USA', 'USA', 'North America'),
  ('DC Hotel SDN BHD (Sofitel Kuala Lumpur Damansara), Malaysia', 'Malaysia', 'Asia'),
  ('Dongseo University, Korea', 'Korea', 'Asia'),
  ('Everbest G & I Pty. Ltd., Australia', 'Australia', 'Oceania'),
  ('Filamer Christian University, Philippines', 'Philippines', 'Asia'),
  ('Fontys University of Applied Sciences, The Netherlands', 'Netherlands', 'Europe'),
  ('Francedia Synvest International Limited, Australia', 'Australia', 'Oceania'),
  ('Fu Jen Catholic University, Taiwan', 'Taiwan', 'Asia'),
  ('Fujian Polytechnic Normal University (FPNU), China', 'China', 'Asia'),
  ('German-Mongolian Institute for Resources and Technology (GMIT), Mongolia', 'Mongolia', 'Asia'),
  ('GUANDATA', 'China', 'Asia'),
  ('Guangdong University of Foreign Studies (GDUFS), China', 'China', 'Asia'),
  ('Guangdong University of Science and Technology (GDUT), China', 'China', 'Asia'),
  ('Guangxi Normal University, P. R. China', 'China', 'Asia'),
  ('Guangzhou College of Commerce, (GCC), China', 'China', 'Asia'),
  ('Guangzhou Huanan Business College, China', 'China', 'Asia'),
  ('Hankuk University of Foreign Studies, Korea', 'Korea', 'Asia'),
  ('Hannam University, Korea', 'Korea', 'Asia'),
  ('Hanze University of Applied Science / Hanzehogeschool Groningen, the Netherlands', 'Netherlands', 'Europe'),
  ('Hochschule Fresenius University of Applied Sciences, Germany', 'Germany', 'Europe'),
  ('Hochschule Mainz - University of Applied Sciences, Germany', 'Germany', 'Europe'),
  ('Hogeschool van Utrecht / Hogeschool Utrecht, the Netherlands', 'Netherlands', 'Europe'),
  ('Holiday Inn Melaka', 'Malaysia', 'Asia'),
  ('Hunan City University, China', 'China', 'Asia'),
  ('I-Shou University, Taiwan', 'Taiwan', 'Asia'),
  ('Inholland University of Applied Sciences / Hogeschool Inholland, The Netherlands', 'Netherlands', 'Europe'),
  ('International Hotel Management Institute (IMI Partners AG Switzerland), Switzerland', 'Switzerland', 'Europe'),
  ('INTI International University, Malaysia', 'Malaysia', 'Asia'),
  ('Iowa State University of Science and Technology (ISU), USA', 'USA', 'North America'),
  ('J&C Homes Hotels SDN. BHD. (Sheraton Petaling Jaya Hotel), Malaysia', 'Malaysia', 'Asia'),
  ('James Cook University (JCU), Singapore', 'Singapore', 'Asia'),
  ('Jayawant Shikshan Prasarak Mandal (JSPM), India', 'India', 'Asia'),
  ('Joongbu University, Korea', 'Korea', 'Asia'),
  ('Josai International University, Japan', 'Japan', 'Asia'),
  ('Kansai Gaidai University, Japan', 'Japan', 'Asia'),
  ('Kansai University of International Studies, Japan', 'Japan', 'Asia'),
  ('Keimyung University, Korea', 'Korea', 'Asia'),
  ('Korea Association of Network Industries (KANI), Korea', 'Korea', 'Asia'),
  ('Lady Doak College, India', 'India', 'Asia'),
  ('Lingnan University, Hongkong', 'Hong Kong', 'Asia'),
  ('Macquarie University, Australia', 'Australia', 'Oceania'),
  ('Massey University, New Zealand', 'New Zealand', 'Oceania'),
  ('MikroTIK, Mikrotikls SIA', 'Latvia', 'Europe'),
  ('Ming Chuan University, Taiwan', 'Taiwan', 'Asia'),
  ('Mit Art, Design, and Technology University (MIT ADTU), India', 'India', 'Asia'),
  ('MNA Consultants PTE, Ltd., Singapore', 'Singapore', 'Asia'),
  ('Monash University, Australia', 'Australia', 'Oceania'),
  ('Mykolas Romeris University, Lithuania', 'Lithuania', 'Europe'),
  ('Myongji University, Korea', 'Korea', 'Asia'),
  ('Nanjing University of Aeronautics and Astronautics (NUAA), China', 'China', 'Asia'),
  ('National Central University, Taiwan', 'Taiwan', 'Asia'),
  ('National Ilan University, Taiwan', 'Taiwan', 'Asia'),
  ('National Kaohsiung University of Science and Technology (NKUST), Taiwan', 'Taiwan', 'Asia'),
  ('National Sun Yat Sen University (NSYSU), Taiwan', 'Taiwan', 'Asia'),
  ('National Taiwan University of Science and Technology (NTUST), Taiwan', 'Taiwan', 'Asia'),
  ('National University of Management (NUM), Cambodia', 'Cambodia', 'Asia'),
  ('New Palace Restaurant, New Palace International Co., LTD, Taiwan', 'Taiwan', 'Asia'),
  ('Ngee Ann Polytechnic (NP), Singapore', 'Singapore', 'Asia'),
  ('Nihon University, Japan', 'Japan', 'Asia'),
  ('Osnabrück University of Applied Sciences, Germany (Faculty of Business Management and Social Sciences)', 'Germany', 'Europe'),
  ('Panpacific University, Philippines', 'Philippines', 'Asia'),
  ('Philippine Christian University, Philippine', 'Philippines', 'Asia'),
  ('Poznań University of Life Science, Poland', 'Poland', 'Europe'),
  ('Professor Robert Peter Mayer, Osnabrück University of Applied Sciences, Germany', 'Germany', 'Europe'),
  ('PT SIKA Indonesia', 'Indonesia', 'Asia'),
  ('Pusan National University, Korea', 'Korea', 'Asia'),
  ('Queensland University of Technology (QUT), Australia', 'Australia', 'Oceania'),
  ('Rajamangala University of Technology Srivijaya, Thailand', 'Thailand', 'Asia'),
  ('Rennes School of Business, France', 'France', 'Europe'),
  ('Royal University of Phnom Penh (RUPP), Cambodia', 'Cambodia', 'Asia'),
  ('Samar State University, Philippines', 'Philippines', 'Asia'),
  ('Saxion University of Applied Sciences, the Netherlands', 'Netherlands', 'Europe'),
  ('School of Economics, Fudan University, China', 'China', 'Asia'),
  ('Shangri La Far Eastern Plaza Hotel, Yuan Ding Co., Ltd., Taiwan', 'Taiwan', 'Asia'),
  ('Sheraton Grand Taipei, My Humble Hospitality Management Consulting Co., LTD, Taiwan', 'Taiwan', 'Asia'),
  ('Shizuoka University, Japan', 'Japan', 'Asia'),
  ('Siam University, Thailand', 'Thailand', 'Asia'),
  ('Silliman University, Philippines', 'Philippines', 'Asia'),
  ('Silpakorn University, Thailand', 'Thailand', 'Asia'),
  ('Singapore Management University (SMU), Singapore', 'Singapore', 'Asia'),
  ('Singapore University of Technology and Design (SUTD), Singapore', 'Singapore', 'Asia'),
  ('Society of Friends of Petra, the Netherlands', 'Netherlands', 'Europe'),
  ('Soongsil University, Seoul, Korea', 'Korea', 'Asia'),
  ('Sophia University, Japan', 'Japan', 'Asia'),
  ('Spaceblossom Yuying Design, Taiwan', 'Taiwan', 'Asia'),
  ('Speedwing Training (Asia) Pte Ltd, Singapore', 'Singapore', 'Asia'),
  ('Srinakharinwirot University (SWU), Thailand', 'Thailand', 'Asia'),
  ('Stefan Cel Mare University of Suceava, Romania', 'Romania', 'Europe'),
  ('Sunway University SDN BHD', 'Malaysia', 'Asia'),
  ('Swan & Maclaren Architects, Singapore', 'Singapore', 'Asia'),
  ('Swinburne University of Technology, Australia', 'Australia', 'Oceania'),
  ('Technische Universitat Ilmenau, Germany', 'Germany', 'Europe'),
  ('Thai-Nichi Institute of Technology, Thailand', 'Thailand', 'Asia'),
  ('The Emirates Academy of Hospitality Management, United Arab Emirates', 'United Arab Emirates (UAE)', 'Middle East'),
  ('The Westin Sanya Haitang Bay Resort, Sanya Minsheng Tourism Industry Co., Ltd., China', 'China', 'Asia'),
  ('Tianjin Foreign Studies University (TFSU), China', 'China', 'Asia'),
  ('Tianjin University, Tianjin, China', 'China', 'Asia'),
  ('Tunghai University, Taiwan', 'Taiwan', 'Asia'),
  ('Tunku Abdul Rahman University of Management and Technology (TARUMT), Malaysia', 'Malaysia', 'Asia'),
  ('Univeristy of Applied Sciences Darmstadt (Hochschule Darmstadt) (h_da), Germany', 'Germany', 'Europe'),
  ('Universidade Nacional Timor Lorosa''e (UNTL), Timor-Leste', 'Timor-Leste', 'Asia'),
  ('Universitas Diponegoro', 'Indonesia', 'Asia'),
  ('Universitas Katolik Soegijapranata', 'Indonesia', 'Asia'),
  ('Universitas Kristen Maranatha', 'Indonesia', 'Asia'),
  ('Universitas Tarumanegara', 'Indonesia', 'Asia'),
  ('Universiti Malaysia Sarawak (UNIMAS), Malaysia', 'Malaysia', 'Asia'),
  ('Universiti Sains Malaysia (USM), Malaysia', 'Malaysia', 'Asia'),
  ('Universiti Teknologi MARA (UiTM), Malaysia', 'Malaysia', 'Asia'),
  ('Universiti Tun Hussein Onn Malaysia (UTHM), Malaysia', 'Malaysia', 'Asia'),
  ('University of Applied Sciences / Christelijke Hogeschool Nederland (CHN), The Netherlands', 'Netherlands', 'Europe'),
  ('University of Chichester, UK', 'UK', 'Europe'),
  ('University of Mindanao, Philippines', 'Philippines', 'Asia'),
  ('University of Saint Joseph, Macau', 'China', 'Asia'),
  ('University of St. La Salle', 'Philippines', 'Asia'),
  ('University of Tasmania, Australia', 'Australia', 'Oceania'),
  ('University of the East', 'Philippines', 'Asia'),
  ('University of the Fraser Valley (UFV), Canada', 'Canada', 'North America'),
  ('Valparaiso University (Valpo), USA', 'USA', 'North America'),
  ('Vellore Institute of Technology (VIT), India', 'India', 'Asia'),
  ('VIT Bhopal University, India', 'India', 'Asia'),
  ('VIT-AP University, India', 'India', 'Asia'),
  ('Wenzao Ursuline University of Languages, Taiwan', 'Taiwan', 'Asia'),
  ('Woosong University, Rep. of Korea', 'Korea', 'Asia'),
  ('World DAGACHI Co.,Ltd, Korea', 'Korea', 'Asia'),
  ('World Skills Academy Sdn Bhd, Malaysia', 'Malaysia', 'Asia'),
  ('Xi''an Jiatong-Liverpool University (XJTLU), China', 'China', 'Asia'),
  ('Xiamen University, China', 'China', 'Asia'),
  ('Xtramile Solutions PTY LTD, Australia', 'Australia', 'Oceania'),
  ('Yangzhou University, China', 'China', 'Asia'),
  ('Yonsei University, Korea', 'Korea', 'Asia'),
  ('Zhejiang Yuexiu University of Foreign Languages, China', 'China', 'Asia')
) as v(name, country, region)
where not exists (
  select 1 from petra_io.partners p where p.name = v.name and p.kind = 'international'
);
